# Usar la imagen base oficial de Node.js
FROM node:18

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos package.json y package-lock.json primero para instalar dependencias
COPY package*.json ./

# Instalar las dependencias
RUN npm install --production

# Copiar el resto de los archivos del proyecto
COPY . .

# Copiar el archivo .env
COPY .env . 

# Exponer el puerto (mismo que usas en tu aplicación)
EXPOSE 4000

# Comando para iniciar la aplicación
CMD ["node", "app.js"]
